# Generated by Django 2.1.7 on 2019-02-16 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0003_auto_20190215_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
