# Generated by Django 2.1.7 on 2019-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0005_node_circuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('battery', 'Battery'), ('resistor', 'Resistor'), ('corner', 'Corner'), ('capacitor', 'Capacitor')], max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
