# Generated by Django 2.1.7 on 2019-02-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0006_auto_20190216_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='value',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
